// Catálogo de departamentos y municipios de la República de Guatemala (22
// departamentos, 340+ municipios). Para el departamento de Guatemala, el
// municipio de Guatemala (la ciudad capital) se subdivide además en zonas.

export const GUATEMALA_DEPARTMENTS: Record<string, string[]> = {
  "Alta Verapaz": [
    "Cobán",
    "Santa Cruz Verapaz",
    "San Cristóbal Verapaz",
    "Tactic",
    "Tamahú",
    "Tucurú",
    "Panzós",
    "Senahú",
    "San Pedro Carchá",
    "San Juan Chamelco",
    "Lanquín",
    "Cahabón",
    "Chisec",
    "Chahal",
    "Fray Bartolomé de las Casas",
    "Santa Catarina La Tinta",
    "Raxruhá",
  ],
  "Baja Verapaz": [
    "Salamá",
    "San Miguel Chicaj",
    "Rabinal",
    "Cubulco",
    "Granados",
    "El Chol",
    "San Jerónimo",
    "Purulhá",
  ],
  Chimaltenango: [
    "Chimaltenango",
    "San José Poaquil",
    "San Martín Jilotepeque",
    "San Juan Comalapa",
    "Santa Apolonia",
    "Tecpán Guatemala",
    "Patzún",
    "Pochuta",
    "Patzicía",
    "Santa Cruz Balanyá",
    "Acatenango",
    "Yepocapa",
    "San Andrés Itzapa",
    "Parramos",
    "Zaragoza",
    "El Tejar",
  ],
  Chiquimula: [
    "Chiquimula",
    "San José La Arada",
    "San Juan Ermita",
    "Jocotán",
    "Camotán",
    "Olopa",
    "Esquipulas",
    "Concepción Las Minas",
    "Quezaltepeque",
    "San Jacinto",
    "Ipala",
  ],
  "El Progreso": [
    "Guastatoya",
    "Morazán",
    "San Agustín Acasaguastlán",
    "San Cristóbal Acasaguastlán",
    "El Jícaro",
    "Sansare",
    "Sanarate",
    "San Antonio La Paz",
  ],
  Escuintla: [
    "Escuintla",
    "Santa Lucía Cotzumalguapa",
    "La Democracia",
    "Siquinalá",
    "Masagua",
    "Tiquisate",
    "La Gomera",
    "Guanagazapa",
    "San José",
    "Iztapa",
    "Palín",
    "San Vicente Pacaya",
    "Nueva Concepción",
  ],
  Guatemala: [
    "Guatemala",
    "Santa Catarina Pinula",
    "San José Pinula",
    "San José del Golfo",
    "Palencia",
    "Chinautla",
    "San Pedro Ayampuc",
    "Mixco",
    "San Pedro Sacatepéquez",
    "San Juan Sacatepéquez",
    "San Raymundo",
    "Chuarrancho",
    "Fraijanes",
    "Amatitlán",
    "Villa Nueva",
    "Villa Canales",
    "San Miguel Petapa",
  ],
  Huehuetenango: [
    "Huehuetenango",
    "Chiantla",
    "Malacatancito",
    "Cuilco",
    "Nentón",
    "San Pedro Necta",
    "Jacaltenango",
    "San Pedro Soloma",
    "San Ildefonso Ixtahuacán",
    "Santa Bárbara",
    "La Libertad",
    "La Democracia",
    "San Miguel Acatán",
    "San Rafael La Independencia",
    "Todos Santos Cuchumatán",
    "San Juan Atitán",
    "Santa Eulalia",
    "San Mateo Ixtatán",
    "Colotenango",
    "San Sebastián Huehuetenango",
    "Tectitán",
    "Concepción Huista",
    "San Juan Ixcoy",
    "San Antonio Huista",
    "San Sebastián Coatán",
    "Santa Cruz Barillas",
    "Aguacatán",
    "San Rafael Petzal",
    "San Gaspar Ixchil",
    "Santiago Chimaltenango",
    "Santa Ana Huista",
    "Unión Cantinil",
    "Santiago Petatán",
  ],
  Izabal: ["Puerto Barrios", "Livingston", "El Estor", "Morales", "Los Amates"],
  Jalapa: [
    "Jalapa",
    "San Pedro Pinula",
    "San Luis Jilotepeque",
    "San Manuel Chaparrón",
    "San Carlos Alzatate",
    "Monjas",
    "Mataquescuintla",
  ],
  Jutiapa: [
    "Jutiapa",
    "El Progreso",
    "Santa Catarina Mita",
    "Agua Blanca",
    "Asunción Mita",
    "Yupiltepeque",
    "Atescatempa",
    "Jerez",
    "El Adelanto",
    "Zapotitlán",
    "Comapa",
    "Jalpatagua",
    "Conguaco",
    "Moyuta",
    "Pasaco",
    "San José Acatempa",
    "Quesada",
  ],
  Petén: [
    "Flores",
    "San José",
    "San Benito",
    "San Andrés",
    "La Libertad",
    "San Francisco",
    "Santa Ana",
    "Dolores",
    "San Luis",
    "Sayaxché",
    "Melchor de Mencos",
    "Poptún",
    "Las Cruces",
    "El Chal",
  ],
  Quetzaltenango: [
    "Quetzaltenango",
    "Salcajá",
    "Olintepeque",
    "San Carlos Sija",
    "Sibilia",
    "Cabricán",
    "Cajolá",
    "San Miguel Sigüilá",
    "Ostuncalco",
    "San Mateo",
    "Concepción Chiquirichapa",
    "San Martín Sacatepéquez",
    "Almolonga",
    "Cantel",
    "Huitán",
    "Zunil",
    "Colomba",
    "San Francisco La Unión",
    "El Palmar",
    "Coatepeque",
    "Génova",
    "Flores Costa Cuca",
    "La Esperanza",
    "Palestina de Los Altos",
  ],
  Quiché: [
    "Santa Cruz del Quiché",
    "Chiché",
    "Chinique",
    "Zacualpa",
    "Chajul",
    "Chichicastenango",
    "Patzité",
    "San Antonio Ilotenango",
    "San Pedro Jocopilas",
    "Cunén",
    "San Juan Cotzal",
    "Joyabaj",
    "Nebaj",
    "San Andrés Sajcabajá",
    "Uspantán",
    "Sacapulas",
    "San Bartolomé Jocotenango",
    "Canillá",
    "Chicamán",
    "Ixcán",
    "Pachalum",
  ],
  Retalhuleu: [
    "Retalhuleu",
    "San Sebastián",
    "Santa Cruz Muluá",
    "San Martín Zapotitlán",
    "San Felipe",
    "San Andrés Villa Seca",
    "Champerico",
    "Nuevo San Carlos",
    "El Asintal",
  ],
  Sacatepéquez: [
    "Antigua Guatemala",
    "Jocotenango",
    "Pastores",
    "Sumpango",
    "Santo Domingo Xenacoj",
    "Santiago Sacatepéquez",
    "San Bartolomé Milpas Altas",
    "San Lucas Sacatepéquez",
    "Santa Lucía Milpas Altas",
    "Magdalena Milpas Altas",
    "Santa María de Jesús",
    "Ciudad Vieja",
    "San Miguel Dueñas",
    "Alotenango",
    "San Antonio Aguas Calientes",
    "Santa Catarina Barahona",
  ],
  "San Marcos": [
    "San Marcos",
    "San Pedro Sacatepéquez",
    "San Antonio Sacatepéquez",
    "Comitancillo",
    "San Miguel Ixtahuacán",
    "Concepción Tutuapa",
    "Tacaná",
    "Sibinal",
    "Tajumulco",
    "Tejutla",
    "San Rafael Pie de la Cuesta",
    "Nuevo Progreso",
    "El Tumbador",
    "El Rodeo",
    "Malacatán",
    "Catarina",
    "Ayutla",
    "Ocós",
    "San Pablo",
    "El Quetzal",
    "La Reforma",
    "Pajapita",
    "Ixchiguán",
    "San José Ojetenam",
    "San Cristóbal Cucho",
    "Sipacapa",
    "Esquipulas Palo Gordo",
    "Río Blanco",
    "San Lorenzo",
    "La Blanca",
  ],
  "Santa Rosa": [
    "Cuilapa",
    "Barberena",
    "Santa Rosa de Lima",
    "Casillas",
    "San Rafael Las Flores",
    "Oratorio",
    "San Juan Tecuaco",
    "Chiquimulilla",
    "Taxisco",
    "Santa María Ixhuatán",
    "Guazacapán",
    "Santa Cruz Naranjo",
    "Pueblo Nuevo Viñas",
    "Nueva Santa Rosa",
  ],
  Sololá: [
    "Sololá",
    "San José Chacayá",
    "Santa María Visitación",
    "Santa Lucía Utatlán",
    "Nahualá",
    "Santa Catarina Ixtahuacán",
    "Santa Clara La Laguna",
    "Concepción",
    "San Andrés Semetabaj",
    "Panajachel",
    "Santa Catarina Palopó",
    "San Antonio Palopó",
    "San Lucas Tolimán",
    "Santa Cruz La Laguna",
    "San Pablo La Laguna",
    "San Marcos La Laguna",
    "San Juan La Laguna",
    "San Pedro La Laguna",
    "Santiago Atitlán",
  ],
  Suchitepéquez: [
    "Mazatenango",
    "Cuyotenango",
    "San Francisco Zapotitlán",
    "San Bernardino",
    "San José El Ídolo",
    "Santo Domingo Suchitepéquez",
    "San Lorenzo",
    "Samayac",
    "San Pablo Jocopilas",
    "San Antonio Suchitepéquez",
    "San Miguel Panán",
    "San Gabriel",
    "Chicacao",
    "Patulul",
    "Santa Bárbara",
    "San Juan Bautista",
    "Santo Tomás La Unión",
    "Zunilito",
    "Pueblo Nuevo",
    "Río Bravo",
    "San José La Máquina",
  ],
  Totonicapán: [
    "Totonicapán",
    "San Cristóbal Totonicapán",
    "San Francisco El Alto",
    "San Andrés Xecul",
    "Momostenango",
    "Santa María Chiquimula",
    "Santa Lucía La Reforma",
    "San Bartolo Aguas Calientes",
  ],
  Zacapa: [
    "Zacapa",
    "Estanzuela",
    "Río Hondo",
    "Gualán",
    "Teculután",
    "Usumatlán",
    "Cabañas",
    "San Diego",
    "La Unión",
    "Huité",
    "San Jorge",
  ],
};

// Zonas activas de la Ciudad de Guatemala (municipio de Guatemala,
// departamento de Guatemala). La numeración va de 1 a 25, pero las zonas
// 20, 22 y 23 nunca se asignaron a territorio del municipio (quedaron en
// Mixco y San Miguel Petapa), por lo que solo existen estas 22 zonas.
export const GUATEMALA_CITY_ZONES = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 21, 24, 25];

export const CAPITAL_DEPARTMENT = "Guatemala";
export const CAPITAL_MUNICIPALITY = "Guatemala";

export function isCapitalCity(department: string, municipality: string): boolean {
  return department === CAPITAL_DEPARTMENT && municipality === CAPITAL_MUNICIPALITY;
}

// Validates a department/municipality/zone triple against the catalog.
// Returns an error message, or null when the sector is valid.
export function validateSector(
  department: string,
  municipality: string,
  zone?: number | null
): string | null {
  const municipalities = GUATEMALA_DEPARTMENTS[department];
  if (!municipalities || !municipalities.includes(municipality)) {
    return "Departamento o municipio inválido";
  }
  if (isCapitalCity(department, municipality)) {
    if (zone == null || !GUATEMALA_CITY_ZONES.includes(zone)) {
      return "Selecciona una zona válida de la Ciudad de Guatemala";
    }
  }
  return null;
}
